### ISSUE TITLE
Regarding Prediction on Independent Test Cohort

### ISSUE THREAD

**Issue by shubhaminnani** [luisvalesilva/multisurv#2]
Hi @luisvalesilva ,
I wanted to infer the model on unseen data, can you please share any plan to share the checkpoint for the model. Also is the Inference Script available as I can't locate.

Can you help. Thanks!

Regards,
Shubham Innani

**Comment by ljhOfGithub** [comment]
Hello, do you use your datasets to run the code successfully?
